# Generated by Django 3.0 on 2022-12-23 09:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Picture',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, null=True, verbose_name='Название картины')),
                ('genre', models.CharField(max_length=70, null=True, verbose_name='Жанр')),
                ('year', models.DateField(null=True, verbose_name='Год написания')),
            ],
        ),
        migrations.AddField(
            model_name='gallery',
            name='city',
            field=models.CharField(max_length=70, null=True, verbose_name='Город'),
        ),
        migrations.AddField(
            model_name='gallery',
            name='country',
            field=models.CharField(max_length=50, null=True, verbose_name='Страна'),
        ),
        migrations.AddField(
            model_name='gallery',
            name='name',
            field=models.CharField(max_length=200, null=True, verbose_name='Название галереи'),
        ),
        migrations.AddField(
            model_name='painter',
            name='country',
            field=models.CharField(max_length=70, null=True, verbose_name='Страна'),
        ),
        migrations.AddField(
            model_name='painter',
            name='name',
            field=models.CharField(max_length=200, null=True, verbose_name='Художник'),
        ),
        migrations.DeleteModel(
            name='Pictures',
        ),
        migrations.AddField(
            model_name='picture',
            name='gallery',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main.Gallery'),
        ),
        migrations.AddField(
            model_name='picture',
            name='painter',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main.Painter'),
        ),
    ]
